python manage.py migrate bioregions 0001 --fake
python manage.py migrate data_distributor 0001 --fake
python manage.py migrate data_manager 0001 --fake
python manage.py migrate depth_range 0001 --fake
python manage.py migrate geographic_report 0001 --fake
python manage.py migrate google-analytics 0001 --fake
python manage.py migrate intersection 0001 --fake
python manage.py migrate layers 0001 --fake
python manage.py migrate mpa 0001 --fake
python manage.py migrate news 0001 --fake
python manage.py migrate replication 0001 --fake
python manage.py migrate screencasts 0001 --fake
python manage.py migrate sharing 0001 --fake
python manage.py migrate simplefaq 0001 --fake
python manage.py migrate staticmap 0001 --fake
python manage.py migrate straightline_spacing 0001 --fake
python manage.py migrate studyregion 0001 --fake
python manage.py migrate user_profile 0001 --fake
python manage.py migrate econ_analysis 0001 --fake
python manage.py migrate ecotrust_layers 0001 --fake
python manage.py migrate mlpa 0001 --fake
python manage.py migrate report 0001 --fake
