# Generated by Django 2.1.7 on 2019-03-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateKml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.FloatField(default=0.0, help_text='Floating point. Higher number = appears higher up on the KML tree.')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('base_kml', models.FilePathField(help_text="\n        Path to KML file.\n        If a superoverlay tree, use relative paths.\n        The user making the request only needs permissions for the base kml.\n        IMPORTANT: Every file in and below the base kml's directory path is accessible\n        if the user has proper permissions on the base kml.", match='\\.km.$', max_length=255, path='/mnt/EBS_superoverlays/display', recursive=True)),
                ('sharing_groups', models.ManyToManyField(blank=True, null=True, to='auth.Group', verbose_name='Share layer with the following groups')),
            ],
        ),
        migrations.CreateModel(
            name='PublicLayerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, help_text='\n        Checking here indicates that this layer list should be the one used in\n        the application. Copies of other layer lists are retained in the\n        system so you can go back to an old version if necessary.\n    ')),
                ('kml_file', models.FileField(help_text='\n        KML file that represents the public layers list. This file can use\n        NetworkLinks pointing to remote kml datasets or WMS servers.\n        For more information on how to create this kml file see the\n        documentation.\n    ', max_length=510, upload_to='layers/uploaded-kml/')),
            ],
        ),
    ]
