# Generated by Django 2.2.1 on 2019-05-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatekml',
            name='sharing_groups',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Share layer with the following groups'),
        ),
    ]
