# Generated by Django 3.2.14 on 2022-07-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasterdataset',
            name='filepath',
            field=models.FilePathField(max_length=255, path='/usr/local/apps/forestplanner/apps/madrona_unused/madrona/raster_stats/test_data', recursive=True),
        ),
    ]
