# Generated by Django 3.2.14 on 2022-07-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='sharing_groups',
            field=models.ManyToManyField(blank=True, editable=False, related_name='bookmarks_bookmark_related', to='auth.Group', verbose_name='Share with the following groups'),
        ),
    ]
