# Generated by Django 2.1.7 on 2019-03-01 16:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Study Region Name')),
                ('active', models.BooleanField(default=False, help_text='This options will usually not be set using the admin interface, but rather by using the management commands relating to study region changes.')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857, verbose_name='Study region boundary')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('lookAt_Lat', models.FloatField(blank=True, default=0, null=True)),
                ('lookAt_Lon', models.FloatField(blank=True, default=0, null=True)),
                ('lookAt_Range', models.FloatField(default=80000, help_text='Distance from lookAt point in meters')),
                ('lookAt_Tilt', models.FloatField(default=0, help_text='Degrees from vertical (0=directly above)')),
                ('lookAt_Heading', models.FloatField(default=0, help_text='View direction in degrees (0=look North)')),
            ],
            options={
                'db_table': 'mm_study_region',
            },
        ),
    ]
