#!/bin/bash

# make sure virtualenv exists first
command -v virtualenv 2>&- || { echo >&2 "I require virtualenv but it's not installed.  Aborting."; exit 1;  }

mkdir repo
cd repo
virtualenv env
cd env
source bin/activate
mkdir src
cd src
git clone git@github.com:Ecotrust/madrona.git
pip install -r madrona/madrona_requirements.txt
cd madrona
python setup.py develop

django-admin.py startproject myproject
cd myproject
django-admin.py startapp myapp

