#!/bin/bash

# make sure virtualenv exists first
command -v virtualenv 2>&- || { echo >&2 "I require virtualenv but it's not installed.  Aborting."; exit 1;  }

virtualenv env
cd env
source bin/activate
mkdir src
cd src
git clone git@github.com:Ecotrust/madrona.git
pip install --upgrade -r madrona/madrona_requirements.txt
cd madrona
python setup.py develop

echo
echo "Your virtualenv is ready"
echo "  source env/bin/activate"
echo "  create-madrona-project.py --help"
