# Generated by Django 2.1.7 on 2019-03-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('precision', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DataNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('archived', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('expected_date', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Layer name (as it appears in the interface)', max_length=100)),
                ('layer_type', models.CharField(choices=[('XYZ', 'XYZ'), ('WMS', 'WMS'), ('ArcRest', 'ArcRest'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('Vector', 'Vector'), ('placeholder', 'placeholder')], help_text='Layer type', max_length=50)),
                ('url', models.CharField(max_length=255, null=True)),
                ('arcgis_layers', models.CharField(blank=True, max_length=255, null=True)),
                ('subdomains', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sublayer', models.BooleanField(default=False)),
                ('legend', models.CharField(blank=True, help_text='URL to legend image', max_length=255, null=True)),
                ('legend_title', models.CharField(blank=True, max_length=255, null=True)),
                ('legend_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('utfurl', models.CharField(blank=True, max_length=255, null=True)),
                ('default_on', models.BooleanField(default=False, help_text='Should layer appear initially on load?')),
                ('description', models.TextField(blank=True, null=True)),
                ('data_overview', models.TextField(blank=True, null=True)),
                ('data_status', models.CharField(blank=True, max_length=255, null=True)),
                ('data_source', models.CharField(blank=True, max_length=512, null=True)),
                ('data_notes', models.TextField(blank=True, null=True)),
                ('bookmark', models.CharField(blank=True, max_length=755, null=True)),
                ('map_tiles', models.CharField(blank=True, max_length=255, null=True)),
                ('kml', models.CharField(blank=True, max_length=255, null=True)),
                ('data_download', models.CharField(blank=True, max_length=255, null=True)),
                ('learn_more', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.CharField(blank=True, max_length=255, null=True)),
                ('fact_sheet', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=512, null=True)),
                ('thumbnail', models.URLField(blank=True, max_length=255, null=True)),
                ('attribute_title', models.CharField(blank=True, max_length=255, null=True)),
                ('compress_display', models.BooleanField(default=False)),
                ('attribute_event', models.CharField(choices=[('click', 'click'), ('mouseover', 'mouseover')], default='click', max_length=35)),
                ('lookup_field', models.CharField(blank=True, max_length=255, null=True)),
                ('vector_color', models.CharField(blank=True, max_length=7, null=True)),
                ('vector_fill', models.FloatField(blank=True, null=True)),
                ('vector_graphic', models.CharField(blank=True, max_length=255, null=True)),
                ('opacity', models.FloatField(blank=True, default=0.5, null=True)),
                ('attribute_fields', models.ManyToManyField(blank=True, null=True, to='layer_manager.AttributeInfo')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LookupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('dashstyle', models.CharField(choices=[('dot', 'dot'), ('dash', 'dash'), ('dashdot', 'dashdot'), ('longdash', 'longdash'), ('longdashdot', 'longdashdot'), ('solid', 'solid')], default='solid', max_length=11)),
                ('fill', models.BooleanField(default=False)),
                ('graphic', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('header_image', models.CharField(blank=True, max_length=255, null=True)),
                ('header_attrib', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, max_length=255, null=True)),
                ('factsheet_thumb', models.CharField(blank=True, max_length=255, null=True)),
                ('factsheet_link', models.CharField(blank=True, max_length=255, null=True)),
                ('feature_image', models.CharField(blank=True, max_length=255, null=True)),
                ('feature_excerpt', models.TextField(blank=True, null=True)),
                ('feature_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='lookup_table',
            field=models.ManyToManyField(blank=True, null=True, to='layer_manager.LookupInfo'),
        ),
        migrations.AddField(
            model_name='layer',
            name='sublayers',
            field=models.ManyToManyField(blank=True, help_text='Select the PARENT layer (which should be checkbox or radio type). Be sure to also check is_sublayer.', null=True, related_name='_layer_sublayers_+', to='layer_manager.Layer'),
        ),
        migrations.AddField(
            model_name='layer',
            name='themes',
            field=models.ManyToManyField(null=True, to='layer_manager.Theme'),
        ),
        migrations.AddField(
            model_name='dataneed',
            name='themes',
            field=models.ManyToManyField(blank=True, null=True, to='layer_manager.Theme'),
        ),
    ]
