# Generated by Django 4.2.2 on 2023-06-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer_manager', '0002_auto_20190529_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='sublayers',
            field=models.ManyToManyField(blank=True, help_text='Select the PARENT layer (which should be checkbox or radio type). Be sure to also check is_sublayer.', to='layer_manager.layer'),
        ),
    ]
