# Generated by Django 2.1.7 on 2019-03-06 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200)),
                ('answer', models.TextField(max_length=2000)),
                ('importance', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
            ],
        ),
        migrations.CreateModel(
            name='FaqGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_group_name', models.CharField(max_length=50)),
                ('importance', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
            ],
        ),
        migrations.AddField(
            model_name='faq',
            name='faq_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplefaq.FaqGroup'),
        ),
    ]
